name: zendo-ai-first-platform

services:
  tasks-db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - tasks_db_data:/var/lib/postgresql/data

  tasks-service:
    build:
      context: .
      dockerfile: tasks-service/Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      tasks-db:
        condition: service_started
    environment:
      - PORT=4002
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tasks-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  bff-service:
    build:
      context: .
      dockerfile: bff-service/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - tasks-service
      - agent-service
    environment:
      - NODE_ENV=development
      - TASKS_SERVICE_URL=http://tasks-service:4002
      - AGENT_SERVICE_URL=http://agent-service:4005

  agent-service:
    build:
      context: .
      dockerfile: agent-service/Dockerfile
    ports:
      - "4005:4005"
    depends_on:
      - mcp-service
    environment:
      - NODE_ENV=development
      - PORT=4005
      - MCP_SERVICE_URL=http://mcp-service:4003
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASEURL=http://langfuse-service:3000

  mcp-service:
    build:
      context: .
      dockerfile: mcp-service/Dockerfile
    ports:
      - "4003:4003"
    depends_on:
      - tasks-service
    environment:
      - NODE_ENV=development
      - PORT=4003
      - TASKS_SERVICE_URL=http://tasks-service:4002
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASEURL=http://langfuse-service:3000

  client:
    build:
      context: .
      dockerfile: client-app/Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - bff-service

  langfuse-service:
    image: langfuse/langfuse:2
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000

  langfuse-db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data

volumes:
  langfuse_db_data:
  tasks_db_data:
